#!/bin/bash
echo "file name?"
read file
echo "command?"
read command
echo "#!/bin/bash" > $file
echo "$command" >> $file
chmod u+x $file
echo "You want to upload the file to git? (1=Si 2=No)"
read response
if $response=1
git add .
echo "Commit?"
read commit
git commit -m $commit
git push
else $response=2
